service:
  name: slack-rustat

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      convertEmptyValues: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DEFAULT_ACCESS_KEY: ${env:DEFAULT_ACCESS_KEY, ''}
    DEFAULT_SECRET: ${env:DEFAULT_SECRET, ''}

resources:
  Resources:
    rustats:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rustats
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: key
            AttributeType: S
          - AttributeName: message
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  helpText:
    handler: src/api/help.get
    events:
      - http:
          method: get
          path: help

  createRustat:
    handler: src/api/rustat.createItem
    events:
      - http:
          method: put
          path: rustat
  deleteRustat:
    handler: src/api/rustat.deleteItem
    events:
      - http:
          method: delete
          path: rustat/{username}/{key}
  listRustats:
    handler: src/api/rustat.listItems
    events:
      - http:
          method: get
          path: rustats/{username}


  # setRustat:
  #   handler: src/api/rusi.createItem
  #   events:
  #     - http:
  #         method: put
  #         path: rusi
  # clearRustat:
  #   handler: src/api/rusi.deleteItem
  #   events:
  #     - http:
  #         method: delete
  #         path: rusi/{username}
  # getUserActiveRustat:
  #   handler: src/api/rusi.getItem
  #   events:
  #     - http:
  #         method: get
  #         path: rusi/{username}
  # listActiveRustats:
  #   handler: src/api/rusi.listItems
  #   events:
  #     - http:
  #         method: get
  #         path: rusis
  # clearAllRustats:
  #   handler: src/api/rusi.deleteAllItems
  #   events:
  #     - http:
  #         method: delete
  #         path: rusis
